export default class _CharacterAttributes implements CharacterAttributes {
	Tsume: number
	akiLeft: number
	akiRight: number
	alignment: StyleRunAlignmentType
	alternateGlyphs: AlternateGlyphsForm
	autoLeading: boolean
	baselineDirection: BaselineDirectionType
	baselinePosition: FontBaselineOption
	baselineShift: number
	capitalization: FontCapsOption
	connectionForms: boolean
	contextualLigature: boolean
	discretionaryLigature: boolean
	figureStyle: FigureStyleType
	fillColor: Color
	fractions: boolean
	horizontalScale: number
	italics: boolean
	kerningMethod: AutoKernType
	language: LanguageType
	leading: number
	ligature: boolean
	noBreak: boolean
	openTypePosition: FontOpenTypePositionOption
	ordinals: boolean
	ornaments: boolean
	overprintFill: boolean
	overprintStroke: boolean
	parent: object
	proportionalMetrics: boolean
	rotation: number
	size: number
	strikeThrough: boolean
	strokeColor: Color
	strokeWeight: number
	stylisticAlternates: boolean
	swash: boolean
	tateChuYokoHorizontal: number
	tateChuYokoVertical: number
	textFont: TextFont
	titling: boolean
	tracking: number
	typename: string
	underline: boolean
	verticalScale: number
	wariChuCharactersAfterBreak: number
	wariChuCharactersBeforeBreak: number
	wariChuEnabled: boolean
	wariChuJustification: WariChuJustificationType
	wariChuLineGap: number
	wariChuLines: number
	wariChuScale: number
}
